GET /api/v1/search
    ?page=1
    &page_size=100
    &search_type=all
    &sort_type=rating
    &order_by=desc
    &name=te HTTP/2.0
Host: localhost:8080
Accept: application/json
Content-Type: application/json
Authorization: Bearer QU5mMjN6bElEYk9jaWZoMDJ1cF9UMmRMSDhoZEhIalE=
