POST /api/v1/library/057ec3f8-83b3-429d-bbe3-83c13e06f99d/folder/228cd70a-1039-430e-a8df-6e6ec7c488d9 HTTP/2.0
Host: localhost:8080
Accept: application/json
Content-Type: application/json
Authorization: Bearer ZzNIemFhaV9mRzl6dW4tLVdWRWlnSG9oZ0x4Rkpsbkk=
