POST /api/v1/folders HTTP/2.0
Host: localhost:8080
Accept: application/json
Content-Type: application/json
Authorization: Bearer UFlzbExteXFRRERPQTdHUjg2MUhqWVVZekdoR1QycDc=


{
  "name": "Subfolder 4",
  "parentFolderId": "830b3090-e2cd-4537-bfbc-2f892f399b2a",
  "userId": "59a5259a-8094-4e8f-8caf-888c3e32f012"
}