POST /api/v1/folders HTTP/2.0
Host: localhost:8080
Accept: application/json
Content-Type: application/json
Authorization: Bearer MUs0ZEI2TkVYbVlIZktfTVBSSTBlclE0ejR6VUpiSVo=

{
  "name": "Test folder1",
  "parentFolderId": "ed95210e-bbf0-4183-9e53-ce3c311083cc"
}