POST /api/v1/folders/ed95210e-bbf0-4183-9e53-ce3c311083cc/decks HTTP/2.0
Host: localhost:8080
Accept: application/json
Content-Type: application/json
Authorization: Bearer OExsUHo2MnpCZjFvRjg4Mm9fcXpKanFHcWRpMTFpTTk=

{
  "name": "Test deck1",
  "parentFolderId": "ed95210e-bbf0-4183-9e53-ce3c311083cc"
}