POST /api/v1/folders HTTP/2.0
Host: localhost:8080
Accept: application/json
Content-Type: application/json
Authorization: Bearer Ul8tcEJMelhZZDkxenhXNDlsYWpfM2oyUmNRTzV6LUQ=


{
  "name": "Test folder4",
  "parentFolderId": "521d2338-f882-485e-89fa-a0c3a8e5baab"
}