GET /api/v1/decks/7f0383eb-9412-47bc-b7dc-4cbf81985195 HTTP/2.0
Host: localhost:8080
Accept: application/json
Content-Type: application/json
Authorization: Bearer UnZqVGVZVW1TeGNsQ3ZqLVR6RlRxQVcta3BoemtfMmc=