GET /api/v1/decks/c48faa4d-aad6-469f-b5e5-e7f1309c3c09 HTTP/2.0
Host: localhost:8080
Accept: application/json
Content-Type: application/json
Authorization: Bearer V2dmOEc0WUpGbTN4TzdzWWNWN2tYbFJxdEp0eTNWNno=