GET /api/v1/decks/00ff477a-f15e-4ebe-bdb2-26c699e166cc HTTP/2.0
Host: localhost:8080
Accept: application/json
Content-Type: application/json
Authorization: Bearer ZE9Oc3Z6QjdVdmNhdlhKTmFaQ2ZUUVdoS3hBdXRvQTU=