GET /api/v1/folders/a5028c10-a3cd-4642-9adf-794778125efc HTTP/2.0
Host: localhost:8080
Accept: application/json
Content-Type: application/json
Authorization: Bearer NG55amZ1cHFNRlRmUERrdzg1akNLdWEwMkd1czFaYlY=