GET /api/v1/folders/521d2338-f882-485e-89fa-a0c3a8e5baab HTTP/2.0
Host: localhost:8080
Accept: application/json
Content-Type: application/json
Authorization: Bearer bGM5ekNhRHNGSGdfVWdsRDQ0Z295MS14THBpNHBWb0U=