GET /api/v1/library/e7400459-54d1-4136-ae65-549c7c7eb5c2 HTTP/2.0
Host: localhost:8080
Accept: application/json
Content-Type: application/json
Authorization: Bearer Wm1TUWxMdE5XVy1Ba3B1WC1WWjBHOFZHNXFzaU82Vms=