PUT /api/v1/repetition HTTP/2.0
Host: localhost:8080
Accept: application/json
Content-Type: application/json

{
  "userId": "46550b99-12d0-4925-b416-3e62fd5b8a16",
  "cardId": "67ca595c-8700-42eb-bfdc-ad68a48604f1",
  "reviewAnswer": "easy"
}