PUT /api/v1/decks/d4bl042f-1296-4e9e-9a8f-0c2f010310da HTTP/2.0
Host: localhost:8080
Accept: application/json
Content-Type: application/json
Authorization: Bearer ZE9Oc3Z6QjdVdmNhdlhKTmFaQ2ZUUVdoS3hBdXRvQTU=

{
  "name": "NEW-NAME"
}