PUT /api/v1/repetition HTTP/2.0
Host: localhost:8080
Accept: application/json
Content-Type: application/json
Authorization: Bearer cUhycE1pMVFJR2hHMEkwN2tqckZPUUJHMU1SNFd6b3Q=

{
  "userId": "59a5259a-8094-4e8f-8caf-888c3e32f012",
  "cardId": "697c8978-9ade-4189-b4ec-56d1b5d77403",
  "reviewAnswer": "good"
}