DELETE /api/v1/tags/59a5259a-8094-4e8f-8caf-888c3e32f012/folder/5261d751-35f2-4347-b93e-3f4b37daee4a HTTP/2.0
Host: localhost:8080
Accept: application/json
Content-Type: application/json
Authorization: Bearer VVpvRnVwaE4td0pPVE4teUtTR2hYT2h5TF9MSXZMdmU=

{
  "tags": ["apple"]
}